name: Publish CI

on:
  release:
    types: [published]

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-22.04
    environment: production
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm test
        env:
          CI: true

      - name: Force upgrade npm to latest
        run: npm install -g npm@latest

      - name: Publish to NPM
        working-directory: './dist/'
        run: |
          VERSION=${{ github.ref_name }}
          CLEAN_VERSION=${VERSION#v}
          npm version $CLEAN_VERSION --no-git-tag-version

          TAG="latest"
          [[ "$VERSION" == *"next"* ]] && TAG="next"
          [[ "$VERSION" == *"rc"* ]] && TAG="rc"

          npm publish --tag $TAG --access public
